from enum import Enum


class WorkSheetColumnEnum(str, Enum):
    PHONES = 'C2:C'
    APPROVALS = 'D2:D'
    SEND_VERIFICATIONS = 'E2:E'
    DATE_FIRST_CONTACT = 'F2:F'
    RESPONSE_VERIFICATION = 'G2:G'
    WPP_EXISTENCE = 'H2:H'


class WorkSheetColumnNameEnum(str, Enum):
    PHONES = 'PHONES'
    APPROVALS = 'APPROVALS'
    SEND_VERIFICATIONS = 'SEND_VERIFICATIONS'
    DATE_FIRST_CONTACT = 'DATE_FIRST_CONTACT'
    RESPONSE_VERIFICATION = 'RESPONSE_VERIFICATION'
    WPP_EXISTENCE = 'WPP_EXISTENCE'
