version: '3'

services:

  chrome:
    image: "selenium/standalone-chrome:latest"
    container_name: "chrome"
    hostname: chrome
    shm_size: '2gb'
    restart: always
    ports:
      - "4444:4444"

  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./docker/postgres/.env

  bot:
      container_name: bot
      restart: always
      build:
        context: .
        dockerfile: ./docker/fastapi/Dockerfile
      env_file:
        - ./docker/fastapi/.env
      volumes:
        - app_volume:/app:z
      depends_on:
        - chrome
        - postgres
      ports:
        - "8000:8000"

volumes:
  app_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./app
